version: "{build}"
branches:
  only:
    - master
    - /v\d+\..+/
    - /release.*/
    - appveyor
shallow_clone: true
os: Visual Studio 2015
configuration:
  - Release
  - RelWithDebInfo

install: |
  appveyor DownloadFile https://github.com/ethereum/cpp-dependencies/releases/download/cache/CUDA-v8.0-WindowsServer2012.zip
  7z x CUDA-v8.0-WindowsServer2012.zip -oC:/
  set PATH=%PATH%;C:/CUDA/v8.0/bin
  nvcc -V
before_build:
  - cmake -G "Visual Studio 14 2015 Win64" -H. -Bbuild -DETHASHCUDA=ON
build_script:
  - cmake --build build --config %CONFIGURATION%
after_build:
  ps: |
    cmake --build build --config $env:configuration --target package
    if ($env:configuration -ne "Release") {
      Get-Item build/ethminer-*-Windows.* | Rename-Item -NewName { $_.name -Replace 'ethminer','ethminer-dbg' }
    }
artifacts:
  - path: build/ethminer-*.zip
    name: ethminer

before_deploy:
  # Read variables dumped by CMake configuration.
  - ps: . build/variables.ps1
deploy:
  # Create GitHub release, also set the release name and description.
  provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: ethminer $(ethminer_version)
  description: ''
  force_update: true  # Force update in case Travis CI created the release before.
  prerelease: $(ethminer_version_is_prerelease)
  draft: false
  artifact: ethminer
  auth_token:
    secure: 0+7jINl9nz0S6/c8kVCUcc9lAalNi+7vjiQU2k4vqB7z+H5y+Kc2YFJ2tQc6brpQ
  on:
    appveyor_repo_tag: true
